### ISSUE TITLE
Test Failures: ApplicationInsights.HostingStartup.Tests.dll

### ISSUE THREAD

**Issue by mikeharder** [aspnet/AzureIntegration#43]
ApplicationInsights.HostingStartup.Tests.dll is failing on OSX-Universe and Ubuntu-Universe for preview1.

```
Test run for /datadrive/2b0c8ce712895332/.r/AzureIntegration/test/Microsoft.AspNetCore.ApplicationInsights.HostingStartup.Tests/bin/Release/netcoreapp2.0/Microsoft.AspNetCore.ApplicationInsights.HostingStartup.Tests.dll(.NETCoreApp,Version=v2.0)
[11:05:34]      Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
[11:05:34]      Copyright (c) Microsoft Corporation.  All rights reserved.
[11:05:34]      
[11:05:34]      Starting test execution, please wait...
[11:06:34]      Testhost process exited with error: Unhandled Exception: System.TypeInitializationException:
The type initializer for 'Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace' threw an exception. --->
System.TypeLoadException: Could not load type 'System.Threading.Monitor' from assembly 
'System.Threading, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
at System.Diagnostics.TraceSource..ctor(String name, SourceLevels defaultLevel)
at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace..cctor()
--- End of inner exception stack trace ---
at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.ShouldTrace(TraceLevel traceLevel)
at Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace.Error(String format, Object[] args)
at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
```

**Comment by pakrym** [comment]
Fixed by https://github.com/aspnet/AzureIntegration/pull/44
